# -*- coding: utf-8 -*-
"""Studying first aid

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169BU6FMvQ6kXUOCzEGOlfXlhG_h1kKYM

## AI First Aid Generator Application

This notebook demonstrates how to build a simple AI-powered first aid generator using Google's Gemini API and Gradio for the user interface. We'll also prepare the necessary files for deployment.

### 1. Set up your Google Gemini API Key

To use the Gemini API, you'll need an API key. If you don't already have one, create a key in [Google AI Studio](https://makersuite.google.com/keys).

In Colab, it's recommended to add your API key to the secrets manager. Click the "🔑" icon in the left panel, search for `GOOGLE_API_KEY`, and paste your key there. This securely stores your key and prevents it from being exposed in your notebook code.
"""

# Import necessary libraries
import google.generativeai as genai
from google.colab import userdata
import gradio as gr
import os

# Configure Generative AI
GOOGLE_API_KEY = userdata.get('GOOGLE_API_KEY')
genai.configure(api_key=GOOGLE_API_KEY)

"""### 2. Initialize the Gemini Model

We'll use the `gemini-pro` model for generating first aid instructions.
"""

# Initialize the Gemini Pro model
model = genai.GenerativeModel('gemini-pro')

"""### 3. Define the First Aid Generation Function

This Python function will take a symptom as input and use the Gemini model to generate relevant first aid instructions. We'll instruct the model to provide concise and clear steps.
"""

def generate_first_aid(symptom: str) -> str:
    """
    Generates first aid instructions for a given symptom using the Gemini Pro model.
    """
    if not symptom.strip():
        return "Please describe a symptom to get first aid instructions."

    prompt = f"""Provide concise and clear first aid instructions for someone experiencing the following symptom or condition: '{symptom}'. Focus on immediate steps and safety. Start directly with the instructions, do not include an introductory sentence like 'Here are first aid instructions...' Make sure to include a disclaimer at the end about seeking professional medical help.
"""

    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"An error occurred while generating first aid: {e}. Please try again later."

"""### 4. Create the Gradio User Interface

Gradio makes it easy to build web interfaces for machine learning models. We'll create an interface with a text input for symptoms and a text output for the first aid instructions.
"""

import gradio as gr

# Create the Gradio interface
iface = gr.Interface(
    fn=generate_first_aid,
    inputs=gr.Textbox(lines=5, label="Describe the symptom or condition"),
    outputs=gr.Textbox(label="First Aid Instructions"),
    title="AI First Aid Generator",
    description="Enter a symptom or condition, and get immediate first aid advice generated by Google's Gemini AI. This is for informational purposes only and not a substitute for professional medical advice. Always consult a healthcare professional for serious conditions."
)

# Launch the Gradio app
# Setting `share=True` generates a public link that can be accessed from outside Colab for a limited time.
print("Launching Gradio interface...")
iface.launch(share=True)
print("Gradio interface launched. Check the public URL above.")

"""### 5. Prepare `app.py` and `requirements.txt` for Deployment

To deploy your application, you'll typically need an `app.py` file containing your application logic and a `requirements.txt` file listing all the Python dependencies. The `app.py` file below is designed to be self-contained for easy deployment, assuming the `GOOGLE_API_KEY` is set as an environment variable in the deployment environment.
"""

import os
import gradio as gr
import google.generativeai as genai
import textwrap

# 1. Configure Gemini API key from environment variable
# The actual API key value should NOT be hardcoded here, but rather retrieved via `userdata.get()` in Colab
# or os.environ.get() in deployment. For local Colab execution, we rely on the global configuration.
# For deployment with app.py, the GOOGLE_API_KEY must be set in the environment.

# Note: This block is for direct execution within this Colab cell.
# The app.py content below will handle API key retrieval for the deployed app.
current_api_key = os.environ.get("GOOGLE_API_KEY") # Attempt to get from env for local check
if not current_api_key:
    # If not found in env (e.g., in a fresh Colab runtime without secrets linked to env), try userdata
    try:
        from google.colab import userdata
        current_api_key = userdata.get('GOOGLE_API_KEY')
    except Exception:
        current_api_key = None

if not current_api_key:
    print("WARNING: GOOGLE_API_KEY not found. Please set it in Colab Secrets or as an environment variable.")
else:
    genai.configure(api_key=current_api_key)

# 2. Initialize the Gemini model
model = genai.GenerativeModel('gemini-pro')

# 3. Define the function to generate first aid instructions
def generate_first_aid(symptom: str) -> str:
    """Generates first aid instructions for a given symptom using the Gemini Pro model."""
    if not symptom.strip():
        return "Please describe a symptom to get first aid instructions."

    # Use the current_api_key for this function call if available
    if not current_api_key:
        return "API Key not configured. Please ensure GOOGLE_API_KEY is set."

    prompt = f"""Provide concise and clear first aid instructions for someone experiencing the following: {symptom}.
    Keep it safe, practical, and add a disclaimer at the end about seeking professional medical help."""
    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"An error occurred while generating first aid: {e}. Please ensure your API key is valid."

# 4. Create the Gradio interface
iface = gr.Interface(
    fn=generate_first_aid,
    inputs=gr.Textbox(lines=2, placeholder="Enter a symptom or condition...", label="Symptom"),
    outputs=gr.Textbox(label="First Aid Instructions"),
    title="AI First Aid Assistant",
    description="Enter a symptom or condition and get immediate first aid guidance."
)

# 5. Launch the app (This block is for local Colab testing and is moved to a previous cell)
# The current cell focuses on generating deployment files, so this launch is removed.

# 6. Save app.py for deployment
app_py_content = """import os
import gradio as gr
import google.generativeai as genai
import textwrap

api_key = os.environ.get("GOOGLE_API_KEY") # Correctly retrieve from environment variable
if not api_key:
    print("ERROR: GOOGLE_API_KEY environment variable not found.")
else:
    genai.configure(api_key=api_key)

model = genai.GenerativeModel('gemini-pro')

def generate_first_aid(symptom: str) -> str:
    \"\"\"Generates first aid instructions for a given symptom using the Gemini Pro model.\"\"\"
    if not symptom.strip():
        return \"Please describe a symptom to get first aid instructions.\"
    if not api_key:
        return \"API Key not configured. Please set the GOOGLE_API_KEY environment variable.\"
    prompt = f\"Provide concise and clear first aid instructions for someone experiencing the following: {symptom}.
    Keep it safe, practical, and add a disclaimer at the end about seeking professional medical help.\"\"
    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f\"An error occurred while generating first aid: {e}.\"

iface = gr.Interface(
    fn=generate_first_aid,
    inputs=gr.Textbox(lines=2, placeholder=\"Enter a symptom or condition...\", label=\"Symptom\"),
    outputs=gr.Textbox(label=\"First Aid Instructions\"),
    title=\"AI First Aid Assistant\",
    description=\"Enter a symptom or condition and get immediate first aid guidance.\"
)

if __name__ == \"__main__\":
    iface.launch(server_name=\"0.0.0.0\", server_port=7860)
"""

with open("app.py", "w") as f:
    f.write(textwrap.dedent(app_py_content))

print("Generated 'app.py' file.")

# 7. requirements.txt
requirements_txt_content = """
gradio
google-generativeai
"""
with open("requirements.txt", "w") as f:
    f.write(requirements_txt_content)
print("Generated 'requirements.txt' file.")

# Content for requirements.txt
requirements_txt_content = """
google-generativeai
gradio
"""

# Save requirements.txt
with open("requirements.txt", "w") as f:
    f.write(requirements_txt_content)

print("Generated `requirements.txt` file.")

"""### 6. Streamlit Deployment Guide (for your Gradio app)

You asked for a Streamlit deployment guide. While Gradio and Streamlit are both frontend frameworks, you can deploy your *Gradio app* to various platforms. If you specifically want to use Streamlit as the *deployment orchestrator* or for another part of your application, here's how you'd typically proceed for a general Streamlit app and how this Gradio app fits in:

**To deploy this Gradio `app.py`:**

1.  **Hugging Face Spaces**: This is a very popular and straightforward way to deploy Gradio apps. Create a new Space, upload your `app.py` and `requirements.txt`, and it will automatically deploy.
2.  **Render.com, Replit, or other PaaS (Platform as a Service)**: These services allow you to deploy Python web applications. You would typically specify a `start` command like `python app.py` and ensure the `GOOGLE_API_KEY` is set as an environment variable in their configuration.

**If you wanted to build a Streamlit app *instead* of a Gradio app for the frontend, or deploy *around* the Gradio app using Streamlit:**

1.  **Create a Streamlit application (`streamlit_app.py`):** If you were to rebuild the UI with Streamlit, your code would look similar to this (but you'd write the UI using `st.text_input`, `st.button`, etc.):

    ```python
    # Example of a Streamlit app (not the Gradio one above)
    import streamlit as st
    import google.generativeai as genai
    import os

    st.set_page_config(page_title="AI First Aid", page_icon="🩹")
    st.title("🩹 AI First Aid Generator")
    st.write("Enter a symptom to get immediate first aid advice.")

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        st.error("API Key not found. Please set the GOOGLE_API_KEY environment variable.")
    else:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-pro')

        def generate_first_aid_streamlit(symptom: str) -> str:
            # ... (same logic as generate_first_aid)
            pass

        symptom_input = st.text_area("Describe the symptom or condition", height=150)

        if st.button("Get First Aid"): # Only execute if button is clicked
            if symptom_input:
                with st.spinner("Generating first aid..."):
                    first_aid_text = generate_first_aid_streamlit(symptom_input)
                    st.markdown("### First Aid Instructions")
                    st.write(first_aid_text)
            else:
                st.warning("Please enter a symptom.")

    st.markdown("---")
    st.info("Disclaimer: This is for informational purposes only and not a substitute for professional medical advice. Always consult a healthcare professional for serious conditions.")
    ```

2.  **Streamlit Cloud Deployment**: Once you have a `streamlit_app.py` (or `app.py` if you rename it) and `requirements.txt` in a GitHub repository:
    *   Go to [Streamlit Cloud](https://share.streamlit.io/).
    *   Connect your GitHub repository.
    *   Select the repository and the main file (e.g., `app.py`).
    *   Add your `GOOGLE_API_KEY` as a secret in Streamlit Cloud's advanced settings (`secrets.toml` or environment variables).
    *   Click "Deploy!" Streamlit Cloud will handle building and running your application.

For your current Gradio application, using a PaaS or Hugging Face Spaces is generally more direct. If you *must* integrate with a larger Streamlit dashboard, you could potentially embed the Gradio app using `streamlit.components.v1.html` once the Gradio app is running and accessible via a URL, but this adds complexity.
"""

!pip install -q -U google-genai gradio